project:
  type: website
  output-dir: docs

website:
  title: "testing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Tutorials"
        href: analysis1.qmd
      - blah.qmd
      - options.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual






